### ISSUE TITLE
I hope the ordinate of chart function can not only display integers, but also display decimals.

### ISSUE THREAD

**Issue by link021** [timstrifler/exclusive-addons-for-elementor#11]
I hope the ordinate of chart function can not only display integers, but also display decimals. It is hoped that the part after the decimal point can be displayed or the actual complete value with decimal point entered can be displayed. Including the tooltip of chart, I also want to display the actual value with decimal point instead of only integer value.
thank you

**Comment by devjennz** [comment]
This enhancement is now supported in Chart widget on **Exclusive Addons Elementor Pro** v1.5.6. Keep in mind that Labels are limited to what can be displayed reasonably within the available space  using the nice numbers algorithm.
