### ISSUE TITLE
Marin error on page

### ISSUE THREAD

**Issue by Olliecord** [timstrifler/exclusive-addons-for-elementor#12]
<img width="826" alt="Screenshot 2022-01-16 at 05 39 43" src="https://user-images.githubusercontent.com/68302704/149648879-96ca7f34-90fd-45c6-87f2-b3dd50efe058.png">

This error is occuring on one of my pages resulting in cutting all margins:

<img width="1730" alt="Screenshot 2022-01-16 at 05 48 27" src="https://user-images.githubusercontent.com/68302704/149648892-d1fedc6f-bbe3-42db-ac3a-f1506938f758.png">

Please help

**Comment by devjennz** [comment]
This issue is fixed since [v2.6.5](https://github.com/timstrifler/exclusive-addons-for-elementor/commit/8e4589a9bd262bc7cdacbe618d6ab8db27b6de22)
