### ISSUE TITLE
Testimonial Carousel RTL Bug

### ISSUE THREAD

**Issue by sliynex** [timstrifler/exclusive-addons-for-elementor#13]
It only shows the first testimonials but when you move to the second page and forward it won't show anything.
I've switched theme which also canceled my RTL and it suddenly worked, but I do need that RTL in my site.

My website for an example:
https://www.mastik.net/newhome
Scroll down until you reach the testimonials :)

**Comment by mmaumio** [comment]
Hi,

Could you please knock in our Live Chat so we can understand the issue and help you resolve better?
https://exclusiveaddons.com/support

Thank You

**Comment by devjennz** [comment]
This issue is fixed since version 1.4.5 in Exclusive Addons Elementor Pro.
