### ISSUE TITLE
Image Magnifier not working on front end

### ISSUE THREAD

**Issue by ahamagi** [timstrifler/exclusive-addons-for-elementor#14]
The Image Magnifier, while working on the back end does not work on the front end of the website... here... https://ahamagi.org/the-land-of-canaan/ Please ADVISE!

**Comment by fahim100** [comment]
Hello,
Do you have any caching plugins installed in your wordpress?
Thank you.

**Comment by ahamagi** [comment]
I have EWWW Image Optimizer... but don't think that's what you mean. Do you have a particular plugin or example of plugins that conflict? Oh and it works fine on the back end editor and preview but nothing on the other end...

**Comment by fahim100** [comment]
Could you please contact our support page? https://exclusiveaddons.com/support/

**Comment by fahim100** [comment]
Could you please knock in our Live Chat so we can understand the issue and help you resolve it better?
https://exclusiveaddons.com/support

**Comment by devjennz** [comment]
This issue is now fixed. Please update Exclusive Addons Elementor to the latest version available or download from [here](https://github.com/timstrifler/exclusive-addons-for-elementor/releases/tag/2.6.9)
