### ISSUE TITLE
big problem

### ISSUE THREAD

**Issue by anillllllllllll** [timstrifler/exclusive-addons-for-elementor#16]
I install [Exclusive Addons For Elementor]plugin and metform automatically disable form not visible

**Comment by mmaumio** [comment]
Hi, 
Could you please share some more information about it?
We have tested Exclusive Addons with Metform:
https://wordpress.org/plugins/metform/

We didn't find any issues with it.

Thank You

**Comment by devjennz** [comment]
It has been a long time waiting for an answer related to the issue with metform plugin. I'm closing this.
