### ISSUE TITLE
My Home Page isn't Working

### ISSUE THREAD

**Issue by PFAGiorgina** [timstrifler/exclusive-addons-for-elementor#18]
Could you please help me resolve this issue?

My navigation menu, flipbox and other json photo or media arent working in my homepage. It affects landing pages. The website URL is: https://www.profitfirstaccounting.com.au/

**Comment by mmaumio** [comment]
Hi,

Could you kindly knock us in our Live Chat support here?
http://exclusiveaddons.com/support

Thank You

**Comment by devjennz** [comment]
Since this issue is fixed in your site, I'm closing this.
