### ISSUE TITLE
Post Grid of Exclusive Addons For Elementor 

### ISSUE THREAD

**Issue by RstWapp** [timstrifler/exclusive-addons-for-elementor#19]
Hello! The Exclusive Addons For Elementor plugin has been activated. The site uses the Post Grid, Enable Load More Button element. When you click on the button, an error appears: <>. The error is shown in the screenshots. How to resolve this error? Thanks, great plugin!
![изображение](https://user-images.githubusercontent.com/114061409/191456760-d82b2396-dc7a-4687-8e91-40cde1922b47.png)
![изображение](https://user-images.githubusercontent.com/114061409/191456292-20248823-7a9a-44d8-9da3-12cba47e611d.png)

**Comment by mmaumio** [comment]
Thank You for the report.
Could you kindly share the URL of the page as well, so we can check?

**Comment by RstWapp** [comment]
Our site is not ready to launch yet. We are working on it and testing its various features. Therefore, access to the site is closed in maintenance mode. Sorry, we can't send the url of this page.

**Comment by devjennz** [comment]
This issue is now fixed. Please update Exclusive Addons Elementor to the latest version available or download from [here](https://github.com/timstrifler/exclusive-addons-for-elementor/releases/tag/2.6.8)
