### ISSUE TITLE
Incompatibility with elementor flexbox container

### ISSUE THREAD

**Issue by colmenareshr** [timstrifler/exclusive-addons-for-elementor#20]
I am working with elementor flexbox container. I needed to create popups for the website and the modal appears behind the sibling elements inside a parent container. 

This does not happen with the default elementor container.

**Comment by mmaumio** [comment]
HI,

Thank you for pointing that out.
Could you please share if you have an URL where we can see how accomplished that?

**Comment by colmenareshr** [comment]
I have [this temporary link ](https://52.67.120.225/ )to show the problem. 

![Captura de pantalla 2022-10-14 184108](https://user-images.githubusercontent.com/14103160/195978799-c028b16c-f807-4c55-a3b8-6b1e4aada016.jpg)

**Comment by devjennz** [comment]
This issue is now fixed. Please update Exclusive Addons Elementor to the latest version available or download from [here](https://github.com/timstrifler/exclusive-addons-for-elementor/releases/tag/2.6.8)
