### ISSUE TITLE
Default image width using shortcode on Modal

### ISSUE THREAD

**Issue by nufrankz** [timstrifler/exclusive-addons-for-elementor#21]
Hello, wonderful plugin, thank you.

I've a question about Modal feature.

I've developed a template using "Elementor Header & Footer Builder" that returned me a shortcode.

My template used custom width of images, as shown below:
![image](https://user-images.githubusercontent.com/8877052/196004789-d2276d9f-914e-4bd3-b7e0-bf1fbaa1ac16.png)

But using this shortcode inside Modal, images are 100% of width, overwriting any custom design made on Elementor, as shown below:
![image](https://user-images.githubusercontent.com/8877052/196004855-ff715789-3cfc-4fe4-949a-a1248f16dcfd.png)

I've looked up your CSS and it's there. Any chance to remove the following code on `/assets/css/exad-styles.min.css` file?

`.exad-modal-item.modal-vimeo .exad-modal-content .exad-modal-element img { width: 100%; display: block } `

Thank you!

**Comment by fahim100** [comment]
Hello,
We reply on crisp.
Thank you

**Comment by devjennz** [comment]
This issue is now fixed. Please update Exclusive Addons Elementor to the latest version available or download from [here](https://github.com/timstrifler/exclusive-addons-for-elementor/releases/tag/2.6.8)
