### ISSUE TITLE
Sticky column does not work 

### ISSUE THREAD

**Issue by webangon** [timstrifler/exclusive-addons-for-elementor#23]
Sticky extension does not work on latest version . 

![download](https://user-images.githubusercontent.com/7946657/210318605-4c89919d-13a0-470f-8329-c56843e9044e.jpg)

**Comment by devjennz** [comment]
This issue is now fixed. Please update Exclusive Addons Elementor to the latest version available or download from [here](https://github.com/timstrifler/exclusive-addons-for-elementor/releases/tag/2.6.8)
