### ISSUE TITLE
No option for responsive in heading widget

### ISSUE THREAD

**Issue by Mistwalk3r** [timstrifler/exclusive-addons-for-elementor#5]
When adding the heading widget, I can't choose to align the heading to the left in desktop mode, and then center it in mobile mode.
See screenshot.
![image](https://user-images.githubusercontent.com/82722997/115120643-d749dc80-9fae-11eb-9dea-abacae1d3db1.png)

**Comment by mmaumio** [comment]
Hi @Mistwalk3r ,
Thank you so much for bringing this to our attention. We're working on it.
I believe you had a chat in our Support with one of our representatives. 
Please keep adding any issues you come up with.

We really appreciate it.

Thank You

**Comment by devjennz** [comment]
This issue is now fixed. Please update Exclusive Addons Elementor to the latest version available or download from [here](https://github.com/timstrifler/exclusive-addons-for-elementor/releases/tag/2.6.8)
