### ISSUE TITLE
Bug on accordion with last version of Elementor pro

### ISSUE THREAD

**Issue by ABsemafor** [timstrifler/exclusive-addons-for-elementor#6]
Recoverable fatal error: Object of class ExclusiveAddons\Elements\Accordion could not be converted to string in /home/clients/0693dfda65b5b933cf10a4fc8f7a540d/sites/dev.semafor-conseil.ch/wp-content/plugins/exclusive-addons-for-elementor/elements/accordion/accordion.php on line 1337

**Comment by mmaumio** [comment]
Thank You so much for opening this issue. We have sorted it out and fixed in our end.
We'll be releasing a bug fix update with it any minute now.
