### ISSUE TITLE
flipbox bug!

### ISSUE THREAD

**Issue by Termy-Dev** [timstrifler/exclusive-addons-for-elementor#7]
Hello, I found this annoying bug, in the flip boxes.
If i don't display any button appears a PHP warring, because I don't use any button, so it's pretty annoying.
I just fixed up by add an @ before the if a row 1088, but every time I update the plugin I have to add the @.

       if(@$settings['exad_flipbox_button_link']['url'] ) {
            $this->add_render_attribute( 'exad_flipbox_button_link', 'href', esc_url( $settings['exad_flipbox_button_link']['url'] ) );
        }
        if(@$settings['exad_flipbox_button_link']['is_external'] ) {
            $this->add_render_attribute( 'exad_flipbox_button_link', 'target', '_blank' );
        }
        if(@$settings['exad_flipbox_button_link']['nofollow'] ) {
            $this->add_render_attribute( 'exad_flipbox_button_link', 'rel', 'nofollow' );
        }

I hope you guys fix this bug. Thanks :D

![Cattura](https://user-images.githubusercontent.com/87690925/126274329-99760e0c-a689-46cb-a5e9-9f2689694f96.PNG)

**Comment by mmaumio** [comment]
Thank You so much for your issue.
We're working on it and will be able to fix this in our next version.

The way you did is suppressing the error by the @ Error Suppression operator.
We're going to resolve the issue by eliminating the error entirely. :)

Thanks Again.

**Comment by devjennz** [comment]
This issue is now fixed in [v2.6.7](https://github.com/timstrifler/exclusive-addons-for-elementor/releases/tag/2.6.7)
