### ISSUE TITLE
Before / After Photo slider bug on RTL

### ISSUE THREAD

**Issue by ja1me4** [timstrifler/exclusive-addons-for-elementor#8]
Hello,

When the website is in RTL, The photo changes but the slider does not move with the before and after photo slider. 

Please see on this link:

https://www.marwabensaid.com/ar/تمرين-شخصي/

**Comment by mmaumio** [comment]
Thank You for pointing this out.
We'll check and get back to you.

**Comment by devjennz** [comment]
This issue belongs to **Exclusive Addons Elementor Pro**. Please download the latest version which includes the fix.
