### ISSUE TITLE
slick-theme fonts missing

### ISSUE THREAD

**Issue by joeygeo** [timstrifler/exclusive-addons-for-elementor#9]
plugin loads slick-theme.min.css, which references slick fonts under vendor/fonts folder. But that folder does not exist.
In fact, those fonts do not exist anywhere in plugin folders.

**Comment by mmaumio** [comment]
Thank You so much for pointing this.
We'll check and update you on this.

**Comment by devjennz** [comment]
This issue belongs to **Exclusive Addons Elementor Pro**. Please download the latest version of **Exclusive Addons Elementor Pro** which includes the fix.
